//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nuclei.Plugins.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nuclei.Plugins.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given export cannot be mapped to the given import..
        /// </summary>
        internal static string Exceptions_Messages_CannotMapExportToImport {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotMapExportToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A discoverable member with the given identity is already registered..
        /// </summary>
        internal static string Exceptions_Messages_DuplicateDiscoverableMember {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DuplicateDiscoverableMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A part with the given type identity is already registered..
        /// </summary>
        internal static string Exceptions_Messages_DuplicatePartDefinition {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DuplicatePartDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type with the given type identity is already registered..
        /// </summary>
        internal static string Exceptions_Messages_DuplicateTypeDefinition {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DuplicateTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified plugin origin is not valid for the current type loader..
        /// </summary>
        internal static string Exceptions_Messages_InvalidPluginOrigin {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InvalidPluginOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter should not be an empty string..
        /// </summary>
        internal static string Exceptions_Messages_ParameterShouldNotBeAnEmptyString {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ParameterShouldNotBeAnEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested export definition was not found..
        /// </summary>
        internal static string Exceptions_Messages_UnknownExportDefinition {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownExportDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested import definition was not found..
        /// </summary>
        internal static string Exceptions_Messages_UnknownImportDefinition {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownImportDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested part definition is not registered..
        /// </summary>
        internal static string Exceptions_Messages_UnknownPartDefinition {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownPartDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of plugin class or interface has not been registered..
        /// </summary>
        internal static string Exceptions_Messages_UnknownPluginType {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownPluginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested type definition is not registered..
        /// </summary>
        internal static string Exceptions_Messages_UnknownTypeDefinition {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownTypeDefinition", resourceCulture);
            }
        }
    }
}
