//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nuclei.Plugins.Discovery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nuclei.Plugins.Discovery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given contract name is already registered..
        /// </summary>
        internal static string Exceptions_Messages_DuplicateContractName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_DuplicateContractName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method marked with the ExportAttribute is not a valid export method..
        /// </summary>
        internal static string Exceptions_Messages_InvalidExportMethod {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InvalidExportMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter should not be an empty string..
        /// </summary>
        internal static string Exceptions_Messages_ParameterShouldNotBeAnEmptyString {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ParameterShouldNotBeAnEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered new rule file at: {0}.
        /// </summary>
        internal static string Log_Messages_FileSystemListener_CreatedFile_WithFilePath {
            get {
                return ResourceManager.GetString("Log_Messages_FileSystemListener_CreatedFile_WithFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanner of type {0} failed to delete the files  [{1}]. The error was {2}..
        /// </summary>
        internal static string Log_Messages_FileSystemListener_DeletedFile_ScannerFailed_WithScannerTypeAndFilePathsAndError {
            get {
                return ResourceManager.GetString("Log_Messages_FileSystemListener_DeletedFile_ScannerFailed_WithScannerTypeAndFileP" +
                        "athsAndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanner of type {0} failed to scan the files  [{1}]. The error was {2}..
        /// </summary>
        internal static string Log_Messages_FileSystemListener_DiscoveredFile_ScannerFailed_WithScannerTypeAndFilePathsAndError {
            get {
                return ResourceManager.GetString("Log_Messages_FileSystemListener_DiscoveredFile_ScannerFailed_WithScannerTypeAndFi" +
                        "lePathsAndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File discovery - Disabled.
        /// </summary>
        internal static string Log_Messages_FileSystemListener_FileDiscovery_Disabled {
            get {
                return ResourceManager.GetString("Log_Messages_FileSystemListener_FileDiscovery_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File discovery - Enabled.
        /// </summary>
        internal static string Log_Messages_FileSystemListener_FileDiscovery_Enabled {
            get {
                return ResourceManager.GetString("Log_Messages_FileSystemListener_FileDiscovery_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered new file at: {0}.
        /// </summary>
        internal static string Log_Messages_FileSystemListener_LocatedFile_WithFilePath {
            get {
                return ResourceManager.GetString("Log_Messages_FileSystemListener_LocatedFile_WithFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered removed file at: {0}.
        /// </summary>
        internal static string Log_Messages_FileSystemListener_RemovedFile_WithFilePath {
            get {
                return ResourceManager.GetString("Log_Messages_FileSystemListener_RemovedFile_WithFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered updated file at: {0}.
        /// </summary>
        internal static string Log_Messages_FileSystemListener_UpdatedFile_WithFilePath {
            get {
                return ResourceManager.GetString("Log_Messages_FileSystemListener_UpdatedFile_WithFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin discovery process completed..
        /// </summary>
        internal static string Plugins_LogMessage_Detector_FileScanCompleted {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Detector_FileScanCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering all the files in {0} failed due to an exception. Exception information is: {1}.
        /// </summary>
        internal static string Plugins_LogMessage_Detector_FileScanFailed_WithDirectoryAndException {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Detector_FileScanFailed_WithDirectoryAndException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering plugins in {0}..
        /// </summary>
        internal static string Plugins_LogMessage_Detector_FileScanStarted_WithDirectory {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Detector_FileScanStarted_WithDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loading of the plugin assembly {0} failed. Exception information is: {1}.
        /// </summary>
        internal static string Plugins_LogMessage_Scanner_AssemblyLoadFailed_WithNameAndException {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Scanner_AssemblyLoadFailed_WithNameAndException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered export: {0}.
        /// </summary>
        internal static string Plugins_LogMessage_Scanner_DiscoveredExport_WithDefinition {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Scanner_DiscoveredExport_WithDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered import: {0}.
        /// </summary>
        internal static string Plugins_LogMessage_Scanner_DiscoveredImport_WithDefinition {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Scanner_DiscoveredImport_WithDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered custom member: {0}.
        /// </summary>
        internal static string Plugins_LogMessage_Scanner_DiscoveredMember_WithDefinition {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Scanner_DiscoveredMember_WithDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load all types from the custom member assembly {0}. Error was: {1}.
        /// </summary>
        internal static string Plugins_LogMessage_Scanner_FailedToLoadCustomMemberTypes_WithAssemblyAndException {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Scanner_FailedToLoadCustomMemberTypes_WithAssemblyAndException" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given discoverable custom member {0} on {1} is not valid. Error was: {2}.
        /// </summary>
        internal static string Plugins_LogMessage_Scanner_InvalidCustomMember_WithMemberNameAndTypeAndException {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Scanner_InvalidCustomMember_WithMemberNameAndTypeAndException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given discoverable custom type {0} is not valid. Error was: {1}.
        /// </summary>
        internal static string Plugins_LogMessage_Scanner_InvalidCustomMember_WithMemberTypeAndException {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Scanner_InvalidCustomMember_WithMemberTypeAndException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given export with contract name {0} on {1} is not valid. Error was: {2}.
        /// </summary>
        internal static string Plugins_LogMessage_Scanner_InvalidExport_WithContractNameAndTypeAndException {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Scanner_InvalidExport_WithContractNameAndTypeAndException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given import with contract name {0} on {1} is not valid. Error was: {2}.
        /// </summary>
        internal static string Plugins_LogMessage_Scanner_InvalidImport_WithContractNameAndTypeAndException {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Scanner_InvalidImport_WithContractNameAndTypeAndException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting information from Assembly {0} failed. Exception information is: {1}.
        /// </summary>
        internal static string Plugins_LogMessage_Scanner_TypeScanFailed_WithAssemblyAndException {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Scanner_TypeScanFailed_WithAssemblyAndException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process export: {0}.
        /// </summary>
        internal static string Plugins_LogMessage_Scanner_UnableToProcessExport_WithContractName {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Scanner_UnableToProcessExport_WithContractName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process export: {0} on a {1}.
        /// </summary>
        internal static string Plugins_LogMessage_Scanner_UnableToProcessExport_WithContractNameAndType {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Scanner_UnableToProcessExport_WithContractNameAndType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process import: {0}.
        /// </summary>
        internal static string Plugins_LogMessage_Scanner_UnableToProcessImport_WithContractName {
            get {
                return ResourceManager.GetString("Plugins_LogMessage_Scanner_UnableToProcessImport_WithContractName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuclei.Plugins.Discovery: plugin scan AppDomain.
        /// </summary>
        internal static string Plugins_PluginScanDomainName {
            get {
                return ResourceManager.GetString("Plugins_PluginScanDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new discoverable member [{0}] to the repository..
        /// </summary>
        internal static string RemoteAssemblyScanner_LogMessage_AddingDiscoverableMemberToRepository_WithMemberInformation {
            get {
                return ResourceManager.GetString("RemoteAssemblyScanner_LogMessage_AddingDiscoverableMemberToRepository_WithMemberI" +
                        "nformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new part [{0}] to repository..
        /// </summary>
        internal static string RemoteAssemblyScanner_LogMessage_AddingPartToRepository_WithPartInformation {
            get {
                return ResourceManager.GetString("RemoteAssemblyScanner_LogMessage_AddingPartToRepository_WithPartInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning assembly [{0}] for plugins..
        /// </summary>
        internal static string RemoteAssemblyScanner_LogMessage_ScanningAssembly_WithName {
            get {
                return ResourceManager.GetString("RemoteAssemblyScanner_LogMessage_ScanningAssembly_WithName", resourceCulture);
            }
        }
    }
}
